var annotated =
[
    [ "Ataque", "class_ataque.html", "class_ataque" ],
    [ "Aviso", "class_aviso.html", "class_aviso" ],
    [ "Back", "class_back.html", "class_back" ],
    [ "BombaEnemigo", "class_bomba_enemigo.html", "class_bomba_enemigo" ],
    [ "Bonus", "class_bonus.html", "class_bonus" ],
    [ "BonusDisparo", "class_bonus_disparo.html", "class_bonus_disparo" ],
    [ "BonusEscudo", "class_bonus_escudo.html", "class_bonus_escudo" ],
    [ "BonusRayo", "class_bonus_rayo.html", "class_bonus_rayo" ],
    [ "BonusVida", "class_bonus_vida.html", "class_bonus_vida" ],
    [ "Boton", "class_boton.html", "class_boton" ],
    [ "BotonCredits", "class_boton_credits.html", "class_boton_credits" ],
    [ "BotonHelp", "class_boton_help.html", "class_boton_help" ],
    [ "BotonPlay", "class_boton_play.html", "class_boton_play" ],
    [ "BotonRecords", "class_boton_records.html", "class_boton_records" ],
    [ "Capitan", "class_capitan.html", "class_capitan" ],
    [ "Coronel", "class_coronel.html", "class_coronel" ],
    [ "Counter", "class_counter.html", "class_counter" ],
    [ "Credits", "class_credits.html", "class_credits" ],
    [ "DisparoBoss", "class_disparo_boss.html", "class_disparo_boss" ],
    [ "DisparoEnemigo", "class_disparo_enemigo.html", "class_disparo_enemigo" ],
    [ "DisparoJugador", "class_disparo_jugador.html", "class_disparo_jugador" ],
    [ "Enemigo", "class_enemigo.html", "class_enemigo" ],
    [ "Escenario", "class_escenario.html", "class_escenario" ],
    [ "Explosion", "class_explosion.html", "class_explosion" ],
    [ "GeneralBoss", "class_general_boss.html", "class_general_boss" ],
    [ "Help", "class_help.html", "class_help" ],
    [ "IronMan", "class_iron_man.html", "class_iron_man" ],
    [ "Kamikase", "class_kamikase.html", "class_kamikase" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "Personaje", "class_personaje.html", "class_personaje" ],
    [ "Rayo", "class_rayo.html", "class_rayo" ],
    [ "ScoreBoard", "class_score_board.html", "class_score_board" ],
    [ "SimpleTimer", "class_simple_timer.html", "class_simple_timer" ]
];